export const initialProducts = [
  {
    id: 1,
    name: 'Premium Cotton T-Shirt',
    price: 29.99,
    originalPrice: 39.99,
    category: 'Clothes',
    subcategory: 'T-Shirts',
    stock: 45,
    description: 'Comfortable premium cotton t-shirt with modern fit',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=300&h=300&fit=crop',
    brand: 'StyleCo',
    rating: 4.5,
    reviews: 128,
    tags: ['cotton', 'casual', 'comfortable'],
    featured: true
  },
  {
    id: 2,
    name: 'Slim Fit Dress Shirt',
    price: 79.99,
    originalPrice: 99.99,
    category: 'Clothes',
    subcategory: 'Shirts',
    stock: 25,
    description: 'Professional slim fit dress shirt for business occasions',
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=300&h=300&fit=crop',
    brand: 'EliteWear',
    rating: 4.7,
    reviews: 89,
    tags: ['formal', 'slim-fit', 'business'],
    featured: false
  },
  {
    id: 3,
    name: 'Casual Denim Jeans',
    price: 89.99,
    originalPrice: 119.99,
    category: 'Clothes',
    subcategory: 'Jeans',
    stock: 35,
    description: 'Classic blue denim jeans with comfortable fit',
    image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=300&h=300&fit=crop',
    brand: 'DenimCraft',
    rating: 4.3,
    reviews: 156,
    tags: ['denim', 'casual', 'classic'],
    featured: true
  },
  {
    id: 4,
    name: 'Luxury Steel Watch',
    price: 299.99,
    originalPrice: 399.99,
    category: 'Watches',
    subcategory: 'Luxury',
    stock: 15,
    description: 'Premium stainless steel watch with sapphire crystal',
    image: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=300&h=300&fit=crop',
    brand: 'TimeElite',
    rating: 4.8,
    reviews: 67,
    tags: ['luxury', 'steel', 'waterproof'],
    featured: true
  },
  {
    id: 5,
    name: 'Sport Digital Watch',
    price: 149.99,
    originalPrice: 199.99,
    category: 'Watches',
    subcategory: 'Sport',
    stock: 28,
    description: 'Durable sport watch with GPS and heart rate monitor',
    image: 'https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=300&h=300&fit=crop',
    brand: 'SportTech',
    rating: 4.6,
    reviews: 94,
    tags: ['sport', 'GPS', 'fitness'],
    featured: false
  },
  {
    id: 6,
    name: 'Classic Leather Sneakers',
    price: 129.99,
    originalPrice: 169.99,
    category: 'Shoes',
    subcategory: 'Sneakers',
    stock: 42,
    description: 'Premium leather sneakers with comfort sole technology',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=300&h=300&fit=crop',
    brand: 'WalkComfort',
    rating: 4.4,
    reviews: 203,
    tags: ['leather', 'comfort', 'casual'],
    featured: true
  },
  {
    id: 8,
    name: 'Running Sports Shoes',
    price: 119.99,
    originalPrice: 149.99,
    category: 'Shoes',
    subcategory: 'Sports',
    stock: 55,
    description: 'Lightweight running shoes with advanced cushioning',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=300&h=300&fit=crop',
    brand: 'RunFast',
    rating: 4.2,
    reviews: 178,
    tags: ['running', 'lightweight', 'cushioning'],
    featured: true
  },
  {
    id: 9,
    name: 'Executive Cologne',
    price: 89.99,
    originalPrice: 119.99,
    category: 'Perfumes',
    subcategory: 'Cologne',
    stock: 33,
    description: 'Sophisticated cologne with woody and citrus notes',
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=300&h=300&fit=crop',
    brand: 'LuxScent',
    rating: 4.6,
    reviews: 112,
    tags: ['woody', 'citrus', 'sophisticated'],
    featured: false
  },
  {
    id: 10,
    name: 'Sport Fresh Deodorant',
    price: 24.99,
    originalPrice: 34.99,
    category: 'Perfumes',
    subcategory: 'Deodorant',
    stock: 67,
    description: '24-hour protection with fresh sport fragrance',
    image: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=300&h=300&fit=crop',
    brand: 'FreshGuard',
    rating: 4.1,
    reviews: 89,
    tags: ['24-hour', 'sport', 'fresh'],
    featured: true
  }
];